export const FEEDBACK_TAG_OPTIONS = [
  { value: "readability", label: "readability" },
  { value: "naming", label: "naming" },
  { value: "style", label: "style" },
  { value: "formatting", label: "formatting" },
  { value: "complexity", label: "complexity" },
  { value: "duplication", label: "duplication" },
  { value: "edge-cases", label: "edge-cases" },
  { value: "null-safety", label: "null-safety" },
  { value: "exception-safety", label: "exception-safety" },
  { value: "performance", label: "performance" },
  { value: "memory", label: "memory" },
  { value: "security", label: "security" },
  { value: "correctness", label: "correctness" },
  { value: "bug-risk", label: "bug-risk" },
  { value: "maintainability", label: "maintainability" },
  { value: "testability", label: "testability" },
  { value: "api-design", label: "api-design" },
  { value: "abstraction", label: "abstraction" },
  { value: "encapsulation", label: "encapsulation" },
  { value: "coupling", label: "coupling" },
  { value: "cohesion", label: "cohesion" },
  { value: "concurrency", label: "concurrency" },
  { value: "io", label: "io" },
  { value: "algorithm", label: "algorithm" },
  { value: "data-structure", label: "data-structure" },
  { value: "documentation", label: "documentation" },
  { value: "logging", label: "logging" },
  { value: "error-handling", label: "error-handling" },
  { value: "validation", label: "validation" },
  { value: "input-sanitization", label: "input-sanitization" },
  { value: "resource-management", label: "resource-management" },
  { value: "time-complexity", label: "time-complexity" },
  { value: "space-complexity", label: "space-complexity" },
  { value: "readability-comments", label: "readability-comments" },
  { value: "modularity", label: "modularity" },
  { value: "dead-code", label: "dead-code" },
  { value: "unused", label: "unused" },
  { value: "other", label: "other" },
] as const;

export type FeedbackTagOption = (typeof FEEDBACK_TAG_OPTIONS)[number];
export type FeedbackTagValue = FeedbackTagOption["value"];
