export const AI_FEEDBACK_ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMIT_UPSTREAM: 'RATE_LIMIT_UPSTREAM',
  RATE_LIMIT_LOCAL: 'RATE_LIMIT_LOCAL',
  UPSTREAM_4XX: 'UPSTREAM_4XX',
  UPSTREAM_5XX: 'UPSTREAM_5XX',
  TIMEOUT: 'TIMEOUT',
  BAD_RESPONSE: 'BAD_RESPONSE',
  REAL_DISABLED: 'REAL_DISABLED',
  MISSING_API_KEY: 'MISSING_API_KEY',
} as const;

export type AiFeedbackProviderErrorCode =
  (typeof AI_FEEDBACK_ERROR_CODES)[keyof typeof AI_FEEDBACK_ERROR_CODES];
