export const CLASSROOM_TASK_STATUS_ACTIVE = 'ACTIVE';
export const CLASSROOM_TASK_STATUS_CLOSED = 'CLOSED';
export const CLASSROOM_TASK_STATUS_RECALLED = 'RECALLED';

export const CLASSROOM_TASK_STATUSES = [
  CLASSROOM_TASK_STATUS_ACTIVE,
  CLASSROOM_TASK_STATUS_CLOSED,
  CLASSROOM_TASK_STATUS_RECALLED,
] as const;

export type ClassroomTaskStatus = (typeof CLASSROOM_TASK_STATUSES)[number];
